spring:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL_EBOOK_SERVICE:jdbc:postgresql://localhost:5432/ebook-database}
    username: ${SPRING_POSTGRES_USERNAME:root}
    password: ${SPRING_POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  application:
    name: ebook-translator

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/realms/ebookTranslator/protocol/openid-connect/certs}

keycloak:
  server-url: ${KEYCLOAK_URL:http://localhost:8081}  # URL de votre Keycloak
  realm: ${CLIENT_REALM:ebookTranslator}
  client-id: ${CLIENT_ID:apiSpring}
  client-secret: ${CLIENT_SECRET:eaegOkdy5VTaDlOoNNnJiXu8HE3zVowm}
