version: '3.8'

services:
  ebook-db:
    image: postgres:16
    container_name: ebook-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ebook-database
    ports:
      - "5432:5432"
    volumes:
      - ebook_pgdata:/var/lib/postgresql/data

volumes:
  ebook_pgdata: